### PR TITLE
Notes for Ubuntu / GForth 0.7.3 Users

### PR DESCRIPTION
**Pull request by RickCarlino**
Hi Gerald,

I finally got `f` running on my system after some attempts. As you noted in #1 , a newer version of GForth was required. After compiling GForth 0.7.3 from source, it seems that `compat-gforth.4th` was not enough to get things running- I needed to backport `{:` and `BUFFER:` in order to get things running on `0.7.3`.

 I have documented the steps in hopes of helping others and to spur adoption from Ubuntu users. If you feel that this PR goes beyond the scope of project goals or is too biased towards Ubuntu users, feel free to close. At the very least, I hope it will serve as a good starting point for Ubuntu users who end up here via Google search.

### CODE REVIEW

**Comment by GeraldWodni** [comment]
I just removed support for `local|` in the last push, should have thought about Gforth 0.7.3 :(

Thanks for your effort 👍 I would very much like to merge your pull-request, however I would prefer if you put all of that in `compat-gforth.4th` instead of a separate file and use `[undefined] ( word ) [if] ( replacement ) [then]`  for `buffer:` and `{:`. That way it can support old Gforth versions without special user intervention. I also think you used `/` instead of `\` for the comments in your source ;)

Would you be happy with doing that?

**Comment by RickCarlino** [comment]
@GeraldWodni Great. I will get to it later tonight.

**Comment by RickCarlino** [comment]
@GeraldWodni I have updated the docs and `comapt-gforth.4th` accordingly. Please let me know if you need anything else!

**Comment by GeraldWodni** [comment]
@RickCarlino nearly perfect, just 2 more things:
1. `{:` is defined by `undefined-value`, `scan-args`, `scan-locals`, ... , which are not officially documented and highly related to the implementation of `{:`. A future implementation of `{:` might use different words, so I think it would look much cleaner if you move `[undefined] {: [if]` to line 10 and remove all the `[undefined] ... [if] ... [then]`s in between. So if Gforth does not feature a `{:` (and only then) you define it using your words.
2. Please add yourself to line 2 and increment the copyright-timespan to 2017, as I will be releasing it right after merging.

**Comment by RickCarlino** [comment]
@GeraldWodni I've:

 * Updated copyright year / authors.
 * Tiny version bump in`package.4th`
 * Group all support words for `{:` under the same `[undefined] {: [if]`

Please let me know if you need anything else.

**Comment by GeraldWodni** [comment]
@RickCarlino thanks for all the effort, I hope I wasn't to pedantic ;)

**Comment by RickCarlino** [comment]
Always happy to help! I will try to get some packages up on the site as time allows.

**Pull request merged**
